# fly.toml app configuration file generated for server-restless-leaf-9857 on 2025-03-27T06:56:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-restless-leaf-9857'
primary_region = 'bom'

[build]

[env]
  PORT = '8080'

# Add volume configuration
[[mounts]]
  source = "score_data"
  destination = "/app/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
